[package]
name = "co-http"
version = "0.1.0"
authors = ["pn"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
actix-web = "2"
actix-rt = "1"
hmac="0.7.1"
sha2="0.8.1"