---

apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: main
  labels:
    comp: app
    env: prod
    optune.ai/exclude: '1'  # don't tune main app

spec:
  replicas: 1
  selector:
    matchLabels:
      comp: app
      env: prod
  template:
    metadata:
      labels:
        comp: app
        env: prod
    spec:
      containers:
      - name: main-cnt
        image: opsani/co-http:latest
        imagePullPolicy: Always
        args: [ 'busy=400' ]
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
          - containerPort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: canary
  labels:
    comp: app
    env: canary
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '8080'

spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      comp: app
      env: canary
  template:
    metadata:
      labels:
        comp: app
        env: canary
    spec:
      containers:
      - name: canary-cnt
        image: opsani/co-http:latest
        args: [ 'busy=400' ]
        resources:
          limits:
            cpu: 250m
            memory: 256Mi
        ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service

metadata:
  name: app

spec:
  type: LoadBalancer
  selector:
    comp: app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---

apiVersion: v1
kind: Service

metadata:
  name: app-canary
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '80'

spec:
  type: ClusterIP
  selector:
    comp: app
    env: canary
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---

apiVersion: v1
kind: Service

metadata:
  name: app-main
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: '/metrics'
    prometheus.io/port: '80'

spec:
  type: ClusterIP
  selector:
    comp: app
    env: prod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
