apiVersion: v1
kind: Secret
metadata:
  name: optune-auth
type: Opaque
data:
  token: ${OPTUNE_AUTH_TOKEN}  # PROVIDE OPTUNE_AUTH_TOKEN ENV VAR: OPTUNE_AUTH_TOKEN=`cat token | base64`
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: optune-servo-prom
  labels:
    comp: optune-servo-prom
    optune.ai/exclude: '1'  # don't tune servo
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      comp: optune-servo-prom
  template:
    metadata:
      labels:
        comp: optune-servo-prom
    spec:
      serviceAccountName: prometheus-k8s
      volumes:
      - name: auth
        secret:
          secretName: optune-auth
      containers:
      - name: main
        image: johnatopsani/servo-k8s-prom:multi-everything-prom
        args:
        - ${OPTUNE_APP_ID}  # PROVIDE OPTUNE_APP_ID ENV VAR
        - '--auth-token=/etc/optune-auth/token'
        env:
        - name: OPTUNE_ACCOUNT
          value: ${OPTUNE_ACCOUNT}  # PROVIDE OPTUNE_ACCOUNT ENV VAR
        - name: OPTUNE_USE_DEFAULT_NAMESPACE
          value: '1'
        volumeMounts:
        - name: auth
          mountPath: '/etc/optune-auth'
          readOnly: true
