---

apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: front
  labels:
    app: twotier
    comp: front

spec:
  replicas: 3
  selector:
    matchLabels:
      app: twotier
      comp: front
  template:
    metadata:
      labels:
        app: twotier
        comp: front
    spec:
      containers:
      - name: main
        image: opsani/co-http:latest
        imagePullPolicy: Always
        args: [ 'busy=5&call=twotier-back' ]
        resources:
          limits:
            cpu: 2000m #250m
            memory: 256Mi
        ports:
          - containerPort: 8080

---

apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: back
  labels:
    app: twotier
    comp: back

spec:
  replicas: 3
  selector:
    matchLabels:
      app: twotier
      comp: back
  template:
    metadata:
      labels:
        app: twotier
        comp: back
    spec:
      containers:
      - name: main
        image: opsani/co-http:latest
        imagePullPolicy: Always
        args: [ 'busy=10' ]
        resources:
          limits:
            cpu: 2000m #250m
            memory: 256Mi
        ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service

metadata:
  name: twotier

spec:
#  type: LoadBalancer
  selector:
    app: twotier
    comp: front
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

---

apiVersion: v1
kind: Service

metadata:
  name: twotier-back

spec:
  selector:
    app: twotier
    comp: back
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

---
